### ISSUE TITLE
Prep weekly ship on Thursday, send on Friday

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#1]
```[tasklist]
### Tasks
- [x] Prep weekly ship on Thursday
- [x] Review with Renata
- [x] Send draft to Jacob
- [x] Send ship to LBS, Emily, Jacob, Anne, Dan, Jonathan, Andrew, Ammie; this team every Friday
```
