### ISSUE TITLE
Content timeliness indicator

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#105]
```[tasklist]
### Tasks
- [x] Review existing research
- [x] Conduct new research if needed
- [x] Add research questions to standards website
- [x] [Draft standard in Google docs for internal sharing](https://docs.google.com/document/d/1JorR7dUwCRNsuIKQbxjXZBtjTmWGQawFgk6lIX-Qbm8/edit#heading=h.45j61zkkhzme)
- [x] Share draft with stakeholders
- [x] [Publish draft to standards website](https://standards.digital.gov/standards/content-timeliness-indicator/)
- [x] Conduct usability testing on the standard
- [x] Revise as needed
- [ ] Decide what the compliance timeline should be
- [ ] Get internal and external approvals to move to pending status
```

**Comment by michelle-rago** [comment]
How should users be informed that translated content isn’t as up-to-date as the English version of the site? (This question could be added to the [GitHub discussion board](https://github.com/GSA-TTS/federal-website-standards/discussions/188).)

**Comment by evoeges** [comment]
Existing research[ summarized here in google docs](https://docs.google.com/document/d/1KRxq3WZ3n67SDGY9Y9bfy2IQpf9RaTxYMgP06TEC9RI/edit?tab=t.0#heading=h.1gee5ww0jpvn). Research [database here in airtable](https://airtable.com/appMcG7ecOC3ALvYt/tbl6ainNSkSXN6Nac/viwVhZoWQ58AaCDgz?blocks=hide).

**Comment by juliaelman** [comment]
@evoeges @michelle-rago @rphillippi after speaking with Elyse, it looks like this Standard is ready to move to Pending based on the research completed. Please confirm.

I also had a good discussion today with Renata about how best to go about the Example section.

**Comment by rphillippi** [comment]
I believe this item is ready to be moved to the next stage.
