### ISSUE TITLE
Content archive indicator

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#106]
```[tasklist]
### Tasks
- [ ] Move from discovery to research; publish research questions
- [ ] Review existing research
- [ ] Conduct new research if needed
- [ ] Draft standard in Google docs for internal sharing
- [ ] Share draft with stakeholders
- [ ] Publish draft to standards website
- [ ] Conduct usability testing on the standard
- [ ] Revise as needed
- [ ] Decide what the compliance timeline should be
- [ ] Get internal and external approvals to move to pending status
```

**Comment by michelle-rago** [comment]
Post to content-managers listserv https://gsa-tts.slack.com/archives/C06S0BW0G4A/p1718717004622819

**Comment by michelle-rago** [comment]
Examples:
- https://github.com/uswds/uswds-site/issues/940
- Some [archive examples](https://docs.google.com/document/d/1pkkDL0Oqe3vHBW81S46P1FiBDHEpGZsMmMvh1HzAlzI/edit#heading=h.y5y3s1c12z2k) (and other timeliness indicators)
