### ISSUE TITLE
External link

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#107]
```[tasklist]
### Tasks
- [x] Review existing research
- [x] Draft [research phase of standard for publication](https://docs.google.com/document/d/1F0eQCp1gJlR3nU8pFQsLD2cu4dUlYaki2BFarhD1PT0/edit#heading=h.45j61zkkhzme)
- [x] Share draft with stakeholders
- [x] Determine if this should be a standard or (as discussed in the Nov. 24 office hours) if this should be part of a broader standard which would cover internal and external links
- [ ] Conduct new research if needed
- [ ] Draft standard in Google docs for internal sharing
- [ ] Share draft with stakeholders
- [ ] Publish draft to standards website
- [ ] Conduct usability testing on the standard
- [ ] Revise as needed
- [ ] Decide what the compliance timeline should be
- [ ] Get internal and external approvals to move to pending status
```

**Comment by michelle-rago** [comment]
https://designsystem.digital.gov/components/link/

USWDS external link research findings from 2021 https://github.com/uswds/uswds/wiki/2021-07-29-External-Link-Indicator-Research-Findings

**Comment by rphillippi** [comment]
Pulling over items from [this ticket on what opens in a new tab and what doesn't](https://github.com/GSA-TTS/federal-website-standards/issues/121) to attach to External Links

https://www.w3.org/TR/WCAG20-TECHS/G200.html

**Comment by juliaelman** [comment]
@rphillippi is further research needed prior to moving this to Draft?

**Comment by rphillippi** [comment]
The page isn't ready to be a draft yet. You could leverage the research that USWDS and other links the team posted to update the content on the page. The page itself doesn't have the information needed to move it forward. I'd check with USWDS about their research and determine if there's more information needed before drafting a standard. Based on what I see, I believe there is.
