### ISSUE TITLE
HTML page title

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#108]
```[tasklist]
### Tasks
- [x] Review existing research
- [x] Conduct new research if needed
- [x] Draft standard in Google docs for internal sharing
- [x] Share draft with stakeholders
- [x] Revise as needed
- [x] [Add draft standard to prototype](https://federalist-142078a8-f654-4daa-8f73-db9770b3ec7a.sites.pages.cloud.gov/site/gsa-tts/federal-website-standards/standards/html-page-title/)
- [x] Complete approval checklist
```

**Comment by michelle-rago** [comment]
- This is an industry-wide best practice
- Agencies think this is reasonable and useful
- Federal guidance could help agencies with internal education
- Guidance that would be helpful include a character limit and going from specific (page content) to general (agency name)
- Page title changes could impact analytics
- Agencies want to keep the standard at a high level (“have a unique page title”)
- Agencies have challenges with implementation
- This is scannable, but we won’t automatically know about the quality of the page title unless we have more sophisticated content analysis tools.
- We could scan for duplicate titles to combat one of the most common issues

**Comment by michelle-rago** [comment]
From M-23:

Agencies’ websites must be structured well; contain rich,
descriptive metadata; feature machine-readable content to the extent practicable; and follow
search engine optimization (SEO) practices to ensure that members of the public can access
government information and services from third-party websites and applications. In addition to
SEO and public discoverability, a well-structured website also can be friendlier to assistive
technology, archival software or services, and for other uses.

**Comment by michelle-rago** [comment]
The pending standard is at https://standards.digital.gov/standards/html-page-title/.
