### ISSUE TITLE
Federal government banner

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#110]
```[tasklist]
### Tasks
- [x] Review existing research
- [x] Conduct new research if needed
- [x] Draft standard in Google docs for internal sharing
- [x] Share draft with stakeholders
- [x] Revise as needed
- [x] [Add draft standard to prototype](https://federalist-142078a8-f654-4daa-8f73-db9770b3ec7a.sites.pages.cloud.gov/site/gsa-tts/federal-website-standards/standards/banner/)
- [x] Complete approval checklist
```

**Comment by michelle-rago** [comment]
The standard is at https://standards.digital.gov/standards/banner/.
