### ISSUE TITLE
Metadata for basic site information

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#113]
```[tasklist]
### Tasks
- [x] Review existing research
- [x] Conduct new research if needed
- [x] [Develop a pilot plan to evaluate the impact of this standard](https://docs.google.com/document/d/1WD3FKHDl3v7gn5GJmnXlM2kgkOv68MvHieCUX9V9-6g/edit)
- [ ] Determine if this will be a standard
```

**Comment by michelle-rago** [comment]
This could be pulled in to the agency identifier standard.

**Comment by rphillippi** [comment]
Per notes on this issue:
- We outlined a pilot plan to evaluate this standard. The goal is for us to evaluate the impact on content discoverability / SEO. [Metadata for basic site information - pilot plan.pdf](https://github.com/user-attachments/files/18854214/Metadata.for.basic.site.information.-.pilot.plan.pdf)
- Lists of agencies: [NARA pointed us to their agency list](https://www.archives.gov/records-mgmt/appraisal/work-group-all.html). [USAGov also has a public list](https://www.usa.gov/agency-index). Both of these lists are available as spreadsheets.
