### ISSUE TITLE
Required links

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#114]
```[tasklist]
### Tasks
- [x] Review existing research
- [x] Conduct new research if needed
- [x] Compile policy questions for OMB
- [x] Conduct research related to OMB responses
- [ ] Discuss legal questions with OGC and OMB (in progress)
```

**Comment by rphillippi** [comment]
[Notes from the policy call with OMB](https://docs.google.com/document/d/1U9AQGppf4zBgpe3M4JtkOecYh6UmgToUbIfNJ-URw1U/edit#heading=h.9cjwtx77o3fi)

**Comment by michelle-rago** [comment]
Example of guidance on mandatory and optional links https://design.canada.ca/common-design-patterns/about-institution.html#design

**Comment by michelle-rago** [comment]
Convo on [link to vote.gov guidance](https://gsa-tts.slack.com/archives/C33CZQG2D/p1723037841503829) (https://www.whitehouse.gov/briefing-room/presidential-actions/2021/03/07/executive-order-on-promoting-access-to-voting/)

**Comment by michelle-rago** [comment]
Next steps for required links:
- Document latest understanding of requirements for each link
- Compile recently redesigned agency sites that handle footers/required links differently
- Propose one or more standards that specify how to comply with policies
- Research with agencies

**Comment by michelle-rago** [comment]
[Common pages and links (DigitalGov draft)](https://docs.google.com/document/d/19E3pNnD6OtGgqUFi3-uMOZlVfO3ZeQeIDL5Z8v3jOgc/edit?tab=t.0#heading=h.oz4q2sh4u6cr)

[Example of required links page that is limited to links mentioned in M-23](https://docs.google.com/document/d/1mHGexyyc9dPU-dWm_-vYFgFjFSwCIruIqXQ4ECE5pKo/edit?tab=t.0)

**Comment by rphillippi** [comment]
We've been waiting on OMB to spend time with their lawyers and our lawyers to iron out the required links. This may be delayed until after the transition.
