### ISSUE TITLE
Location of common utilities (e.g., search, login/sign in, language selection)

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#115]
```[tasklist]
### Tasks
- [x] Review existing research
- [x] Conduct new research if needed
- [x] Experiment with separating these elements into their own standards
- [ ] https://github.com/GSA-TTS/federal-website-standards/issues/154
- [ ] https://github.com/GSA-TTS/federal-website-standards/issues/155
```

**Comment by michelle-rago** [comment]
- A 10x team researched language access with monolingual Arabic, Chinese, and Spanish speakers. All Chinese and Spanish users, and some Arabic users, expect to find the language selector in the upper right corner on desktop and mobile. 
- Some users assumed that no language options were available if they did not appear at the top of the page.
- One agency team mentioned that guidance for utilities focusing on a mobile display would be useful.
- There is a lot of variation on language selectors and the order in which utilities appear.

**Comment by michelle-rago** [comment]
Research on contact pages https://www.nngroup.com/articles/contact-us-pages/

**Comment by michelle-rago** [comment]
Search guidance from M-23:

"Use on-site search functionality: Agencies’ public-facing websites must contain a
search function that allows users to easily search content intended for public use. This
search function should be a site-wide global search and, when appropriate, could be a
feature-specific search for a subset of the website content that is of significant public interest (e.g., find-a-form tool). Agencies should participate in the Search.gov program by
utilizing Search.gov for on-site search solutions or by integrating search solutions with Search.gov.

• Design search-engine optimized content: Agencies should ensure that publicly
available content (i.e., content that does not require user authentication or sign in) is
designed and structured so it can be effectively crawled and indexed by search engines.
Agencies must not limit which search engines or crawlers can access or archive their
public content. Agencies should employ best practices to improve crawling or indexing
of web content, including using sitemaps, robots.txt files,29 and descriptive metadata in
commonly parsed fields (e.g., meta element tags). "

**Comment by rphillippi** [comment]
@michelle-rago can we make the separated items sub items of this one?

**Comment by michelle-rago** [comment]
> [@michelle-rago](https://github.com/michelle-rago) can we make the separated items sub items of this one?

They are sub-items. Is there some other type of display you were thinking of?

**Comment by michelle-rago** [comment]
We don't see the value in presenting these utilities as a standard. We're handling them separately for now. The upcoming work on the header will likely incorporate these utilities as well.
