### ISSUE TITLE
Agency identifier

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#116]
```[tasklist]
### Tasks
- [x] Review existing research
- [x] Draft [research phase of standard for publication](https://docs.google.com/document/d/1K7ns5T9zY3AHThWu97ta-puttP3o4ZKT4lo7ZNnS7kY/edit#heading=h.uvgnqldirywn)
- [ ] Determine if this will be a standard
- [ ] If yes, determine the scope of the standard
```

**Comment by michelle-rago** [comment]
The word "identifier" has other meanings in the web context. Can we be more explicit here if we mean agency name or agency logo?

**Comment by michelle-rago** [comment]
Next steps for agency identfier
- Draft message for DX Council listserv asking for agency input
- Ask agencies about their preferences for the scope of agency identifier; provide options for thinking about identifier more broadly (including other branding aspects)
