### ISSUE TITLE
Links: inline text and styling

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#117]
Function: User can identify and understand link text

Implementation considerations: How should links and buttons look, what do they do, etc. For example "all links need to be underlined" or "a button needs an outline around it". Should we just point towards WCAG as opposed to doing anything on our end? Does OMB just need to enforce?

```[tasklist]
### Tasks
- [ ] Review existing research
- [ ] Determine the scope of this standard
- [ ] Decide if a standard is needed
```

**Comment by michelle-rago** [comment]
https://webaim.org/techniques/hypertext/link_text
