### ISSUE TITLE
Language selector

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#122]
```[tasklist]
### Tasks
- [x] Move from discovery to research; publish research questions
- [x] Review existing research (including 10x report on improving language access)
- [ ] Meet with Login.gov UX
- [ ] Identify other TTS SMEs (vote.gov, usa.gov, 10x)
- [ ] Conduct new research if needed
- [ ] Draft standard in Google docs for internal sharing
- [ ] Share draft with stakeholders
- [ ] Publish draft to standards website
- [ ] Conduct usability testing on the standard
- [ ] Revise as needed
- [ ] Decide what the compliance timeline should be
- [ ] Get internal and external approvals to move to pending status
```

**Comment by michelle-rago** [comment]
https://designsystem.digital.gov/components/language-selector/

**Comment by michelle-rago** [comment]
A 10x team researched language access with monolingual Arabic, Chinese, and Spanish speakers. All Chinese and Spanish users, and some Arabic users, expect to find the language selector in the upper right corner on desktop and mobile.
Some users assumed that no language options were available if they did not appear at the top of the page.
One agency team mentioned that guidance for utilities focusing on a mobile display would be useful.
There is a lot of variation on language selectors and the order in which utilities appear.
