### ISSUE TITLE
Content management for the standards site

### ISSUE THREAD

**Issue by rphillippi** [GSA-TTS/federal-website-standards#130]
How will this be done post 18F?

This is for the development of our website and a CMS, if that turns out to be an option. 

While we need to make the decision about where this lives, we need to also understand the following, especially in regards to staffing the program:
- Who updates the content? Do we do it ourselves?
- Can we leverage USWDS/Digital.gov teams for the updates?
- What's the process?
- What do we need ongoing if we're only updating the site every x number of months?
```[tasklist]
### Tasks
- [x] Update [content guide with details about maintaining the site](https://docs.google.com/document/d/1ymwomD0rnwQH-WbNJuyATHQ3_ROhkpEXYDnAbarCReg/edit#heading=h.y4w9218vwxrp) @michelle-rago
- [ ] Identify how the website will get updated after 18F rolls off
- [ ] Review content guide @renata-phillippi
```

**Comment by rphillippi** [comment]
This is for the development of our website and a CMS, if that turns out to be an option.

**Comment by michelle-rago** [comment]
@rphillippi @evoeges Can you [review the content guide](https://docs.google.com/document/d/1ymwomD0rnwQH-WbNJuyATHQ3_ROhkpEXYDnAbarCReg/edit#heading=h.y4w9218vwxrp) and let me know what else you think needs to be there? The purpose of this guide is to support folks who will maintain the standards website.
