### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#154]
```[tasklist]
### Tasks
- [x] Review existing research
- [x] Conduct new research if needed
- [x] Add research questions to standards website
- [x] [Draft standard in Google docs for internal sharing](https://docs.google.com/document/d/1Y-QkFfzODu5x01Z9Nnlt-ZNWYt8e_hD8TwuNBb3Hosk/edit#heading=h.45j61zkkhzme)
- [x] Share draft with stakeholders
- [x] Develop draft standard
- [x] [Publish draft to standards website](https://standards.digital.gov/standards/contact-page/)
- [x] Conduct usability testing on the standard
- [x] Revise as needed
- [x] Decide what the compliance timeline should be
- [ ] Get internal and external approvals to move to pending status
```

**Comment by michelle-rago** [comment]
Research on contact pages https://www.nngroup.com/articles/contact-us-pages/

From M-23:

"Maintain non-digital interaction options: Agencies must always maintain an accessible
method (i.e., physical availability) for completing a digital service through in-person,
paper-based, or other means, so customers without the ability to use a digital service are
not deprived of or impeded in their ability to access it. This means that agencies should
afford the public the ability to complete a transaction over at least one traditional service
channel (e.g., in person, postal mail, or phone)."

**Comment by michelle-rago** [comment]
Follow https://www.ftc.gov/news-events/news/press-releases/2023/03/federal-trade-commission-proposes-rule-provision-making-it-easier-consumers-click-cancel-recurring for impact.

**Comment by michelle-rago** [comment]
Guidance on phone numbers https://www.smashingmagazine.com/2022/09/phone-numbers-web-designers/

**Comment by evoeges** [comment]
Existing research [summarized here in google docs](https://docs.google.com/document/d/1KRxq3WZ3n67SDGY9Y9bfy2IQpf9RaTxYMgP06TEC9RI/edit?tab=t.0#heading=h.1gee5ww0jpvn). Research [database here in airtable](https://airtable.com/appMcG7ecOC3ALvYt/tbl6ainNSkSXN6Nac/viwVhZoWQ58AaCDgz?blocks=hide).

**Comment by rphillippi** [comment]
There has been one comment about having cleaned up email addresses in discussions but otherwise no movement. I think we can move this one forward.

**Comment by michelle-rago** [comment]
I agree that this one can move forward. Are you still planning to have a "required by" date for pending standards though?

**Comment by juliaelman** [comment]
@michelle-rago to my knowledge, we will continue to have a "required by" for all pending standards.

**Comment by juliaelman** [comment]
Started PR here to move "Contact Page" into Pending status
