### ISSUE TITLE
Schedule interview with State

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#20]
```[tasklist]
### Tasks
- [x] Determine if we can use Google Meet
- [x] Schedule meeting for Tuesday, 4:30-5:30
- [x] Invite Jeffrey, Monica, Hannah
```
