### ISSUE TITLE
Invite an internal team to participate

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#22]
```[tasklist]
### Tasks
- [x] Send Kelsey invite message
- [x] Get a POC (Sarah Rudder / Sven Aas)
- [ ] Set up intro call/interview
```
