### ISSUE TITLE
LibreJS compatibility

### ISSUE THREAD

**Issue by cooljeanius** [GSA-TTS/federal-website-standards#264]
```[tasklist]
### Tasks
- [ ] Review existing research
- [ ] Conduct new research if needed
- [ ] Draft standard in Google docs for internal sharing
- [ ] Share draft with stakeholders
- [ ] Revise as needed
```
GNU LibreJS is a browser extension for ensuring the freeness of JavaScript encountered on websites: [https://www.gnu.org/software/librejs/](https://www.gnu.org/software/librejs/)
When used on [standards.digital.gov](https://standards.digital.gov/), it reports blocking 2 scripts due to missing license info:
<img width="1117" alt="Screen Shot 2024-10-01 at 18 45 12" src="https://github.com/user-attachments/assets/6d5bd647-2627-4959-95ea-5b28357a7d9f">
Specifically:
- https://search.usa.gov/assets/sayt_loader.js - External script with no known license
- https://standards.digital.gov/assets/js/app-B6YTG4NS.js - External script with no known license
Steps to free your JavaScript are identified at these links:
- https://www.gnu.org/software/librejs/free-your-javascript.html
- https://www.gnu.org/software/librejs/manual/html_node/Setting-Your-JavaScript-Free.html
