### ISSUE TITLE
Draft comms for weekly leadership reporting

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#3]
```[tasklist]
### Tasks
- [ ] Determine if this needs to be separate from the weekly ship
- [ ] Send draft to Jacob
- [ ] Determine when this will be sent and who should receive it
```
