### ISSUE TITLE
Merge existing standards pages into USWDS format

### ISSUE THREAD

**Issue by cannandev** [GSA-TTS/federal-website-standards#44]
```[tasklist]
### Tasks
- [x] Get USWDS 3.0 running
- [ ] Create a few 11ty templates to start
- [ ] Move existing draft content to 11ty folders
- [ ] Review with team
```
