### ISSUE TITLE
Launch banner research test

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#49]
```[tasklist]
### Tasks
- [x] FInalize research plan
- [x] Create test in UserTesting
- [x] Test with one user
- [x] Edit as needed; launch full test
```
