### ISSUE TITLE
Prep for OMB check in

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#5]
```[tasklist]
### Tasks
- [ ] Draft agenda by Monday morning
- [ ] Assign a notetaker
- [ ] Send agenda to attendees if it's different from the standard agenda
- [ ] Send any questions to OMB Monday morning (at the latest)
```
