### ISSUE TITLE
Synthesize agency research

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#59]
Let's start synthesizing agency research so we can more easily apply and share what we're learning.

```[tasklist]
### Tasks
- [x] Create plan, process for synthesizing agency research
- [x] Share with team
- [x] Start synthesizing previous interviews
- [ ] Recommend steps for notetakers, observers to help with synthesis
```
