### ISSUE TITLE
Develop a script for agency (+ big 6 websites) interviews

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#6]
```[tasklist]
### Tasks
- [x] Draft agency research plan
- [x] Share with team
- [ ] Share with OMB
```
