### ISSUE TITLE
Share research

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#70]
```[tasklist]
### Tasks
- [x] Send Rachel trust research
- [ ] Send Matt banner research
- [ ] Get GSA 21C compliance scanning from Rachel
```
