### ISSUE TITLE
Update prototype templates

### ISSUE THREAD

**Issue by cannandev** [GSA-TTS/federal-website-standards#73]
```[tasklist]
### Tasks
- [ ] Display H1 titles
- [ ] Adjust width of prose text
- [ ] Create a "list" template to display published standards
- [ ] Break out standards into individual markdown files
```
