### ISSUE TITLE
Prototype build steps

### ISSUE THREAD

**Issue by cannandev** [GSA-TTS/federal-website-standards#74]
```[tasklist]
### Tasks
- [ ] Identify different page types and layouts
- [ ] Add script to optimize Markdown images
- [ ] Schedule "Team test time" (a11y manual tests)
- [ ] Set footer and identifier links in site.yaml
- [ ] https://github.com/GSA-TTS/federal-web-standards/issues/78
- [ ] Explore content management options for maintenance
- [ ] Add dap agency info and ga id
- [ ] Set site-level and page-level meta data  (OG and Twitter images, description, etc)
- [ ] Configure site search.gov and search results page
- [ ] Review Before you launch checklist
- [ ] Update README.md with instructions to run site locally
```
