### ISSUE TITLE
Set up banner impact test in UserTesting

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#8]
```[tasklist]
### Tasks
- [x] Draft research plan
- [x] Get access to UserTesting to create test
- [x] Test the test
- [x] Make any changes
- [x] Launch full test
```
